get http://localhost:4444/user


###
post http://localhost:4444/user
Content-Type: application/json

{
    "uname":"Ganesh",
    "umobile":"8989898989",
    "uemail":"abc@gmail.com",
    "uaddress":"Mumbai Maharashtra"
}


###
get http://localhost:4444/user/660ff10212455e245ece1c9a